platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: bookit-prototype-1

run:
  path: bookit-prototype-1/concourse/scripts/build_android.sh